image: sotirisp/supereight-ci:18.04

pipelines:
  branches:
    '{master, devel}':
    - step:
        script:
          - git submodule update --init --recursive
          - make test
          - make install
          - make test-install

