image: sotirisp/supereight-ci:18.04

pipelines:
  branches:
    '{master, devel}':
    - step:
        script:
          - git submodule update --init --recursive
          - GTEST_ROOT=/usr/local/src/googletest/googletest/ make test

