image: sotirisp/supereight-testing:latest

pipelines:
  default:
    - step:
        script:
          - sed -i 's|\.\./srl_projection\.git|git@bitbucket.org:smartroboticslab/srl_projection\.git|' .gitmodules
          - git submodule update --init --recursive
          - GTEST_ROOT=/usr/local/src/googletest/googletest/ make
          - GTEST_ROOT=/usr/local/src/googletest/googletest/ make test

