voxel_impl:
  surface_boundary:           0.0
  occupancy_min_max:          [-100, 100]
  max_weight:                 100
  free_space_integr_scale:    0
  const_surface_thickness:    false  # if true, surface thickness := max_surface_thickness
  tau_min_max:                [0.06, 0.16]
  k_tau:                      0.026
  uncertainty_model:          quadratic # { linear, quadratic }
  sigma_min_max:              [0.005, 0.02]  # minimum/maximum uncertainty := 3 x sigma_min/sigma_max
  k_sigma:                    0.0016

